title: What Sort of People Should There Be?
email: ben@notionparallax.co.uk
description: "GENETIC ENGINEERING, BRAIN CONTROL, AND THEIR IMPACT ON OUR FUTURE WORLD"
baseurl: "/people" # the subpath of your site, e.g. /blog
url: "http://notionparallax.github.io" # the base hostname & protocol for your site
twitter_username: notionparallax
github_username:  notionparallax

# Build settings
markdown: kramdown
